# [versions] 部分用于声明可以被依赖项引用的版本
# [libraries] 部分用于声明 Library 的别名
# [bundles] 部分用于声明依赖包
# [plugins] 部分用于声明插件

[versions]
# android defaultConfig
minsdk = "24"
targetsdk = "31"
compilesdk = "31"
versioncode = "103"
versionname = "1.0.3"

# SDK
kotlin = "1.6.10"
lifecycle = "2.4.0"
retrofit = "2.9.0"
glide = "4.12.0"

[libraries]
# androidX
core-ktx = "androidx.core:core-ktx:1.7.0"
appcompat = "androidx.appcompat:appcompat:1.3.1"
material = "com.google.android.material:material:1.4.0"
fragment = "androidx.fragment:fragment-ktx:1.4.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.1"
recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
cardview = "androidx.cardview:cardview:1.0.0"

# lifecycle 生命周期管理
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# BaseRecyclerView
baserecyclerview = "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.7"
# 腾讯 mmkv
mmkv = "com.tencent:mmkv:1.2.11"
# 工具类
utilcodex = "com.blankj:utilcodex:1.30.6"
# popup 弹窗
basepopup = "io.github.razerdp:BasePopup:3.2.0"
# permissionx
permissionx = "com.guolindev.permissionx:permissionx:1.6.0"
# 连点 防抖动
rxbinding = "com.jakewharton.rxbinding4:rxbinding:4.0.0"
# material-dialogs
commons-dialogs = "com.afollestad.material-dialogs:commons:0.9.6.0"
# splashscreen
splashscreen = "androidx.core:core-splashscreen:1.0.0-alpha02"
# PersistentCookieJar
persistent-cookie-jar = "com.github.franmontiel:PersistentCookieJar:v1.0.1"
# AgentWeb
agentWeb = "com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha.1-androidx"
# okhttp 日志拦截器
logging-interceptor = "com.squareup.okhttp3:logging-interceptor:4.9.2"
# RxAndroid
rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.0"
# retrofit RxJava2 + retrofit2 + RxBinding。注意，RxBinding内包含RxJava2，所以不要再次引入RxJava2依赖
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }

# Glide 图片加载、缓存、转换
glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-transformations = "jp.wasabeef:glide-transformations:4.3.0"

[bundles]
glide = ["glide-core", "glide-compiler", "glide-transformations"]
androidx = ["core-ktx", "appcompat", "material", "fragment", "constraintlayout", "recyclerview", "cardview"]
lifecycle = ["lifecycle-runtime", "lifecycle-livedata", "lifecycle-viewmodel"]
retrofit = ["retrofit", "converter-gson", "converter-scalars", "adapter-rxjava3"]